---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-project
  labels:
    app: lms-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lms-project
  template:
    metadata:
      labels:
        app: lms-project
    spec:
      containers:
      - name: cont-1
        image: maheesh1/custom-app:11
        ports:
        - containerPort: 8080

  

